DRAFT minutes for 2024-04-10
PQCA/TAC pull request #10
Opened 2024-04-10 23:35 UTC by maximilien

Added DRAFT minutes for review and approvals

2024-04-11 06:00 UTC, thb-sb approved these changes
thanks @maximilien! \o/

2024-04-22 13:23 UTC, maximilien commented
Any chance for approval @ashman-p or @thb-sb or @ryjones so I can merge.

Thanks

2024-04-22 13:53 UTC, ashman-p requested changes

2024-04-22 13:53 UTC, ashman-p commented on meeting-minutes/2024/2024-04-10-TAC.md
>  * [ ] ~~Norman Ashley, Cisco~~
```suggestion
* [x] ~~Norman Ashley, Cisco~~
```

2024-04-22 13:53 UTC, ashman-p commented on meeting-minutes/2024/2024-04-10-TAC.md
> +* Norm ()
```suggestion

```

2024-04-22 14:14 UTC, ashman-p approved these changes

2024-04-23 18:51 UTC, ryjones commented
@maximilien I think you can merge now?

2024-04-24 14:49 UTC, sam-stanwyck approved these changes

2024-04-30 18:04 UTC, maximilien commented
Interesing @ryjones I don't see a merge option (button). What gives?

2024-04-30 18:22 UTC, merged

2024-04-30 19:49 UTC, maximilien commented
Thanks @ryjones

2024-04-30 20:14 UTC, ryjones commented
@maximilien you have not accepted your invite to join the PQCA org, which is why you don't have a merge button
<img width="1009" alt="Screenshot 2024-04-30 at 13 11 56" src="https://github.com/PQCA/TAC/assets/466142/6c5e70e7-fb12-4092-9ff7-a7e7af9284f7">