Create 2024-07-03.md
PQCA/TAC pull request #30
Opened 2024-07-12 00:23 UTC by maximilien

Initial minutes for 07/03 meeting

2024-07-12 00:24 UTC, maximilien commented
Please peruse and suggest changes or approve

cc: @brian-jarvis-aws @planetf1 @hartm @Naomi-Wash @ryjones

2024-07-16 14:21 UTC, brian-jarvis-aws requested changes
Left a couple nitpicky spelling corrections, but the blocking item is to correct the date (line 3).

2024-07-16 14:21 UTC, brian-jarvis-aws commented on meeting-minutes/2024/2024-07-03.md
> +title: 2024-06-05 TAC Meeting Record
```suggestion
title: 2024-07-03 TAC Meeting Record
```

2024-07-16 14:21 UTC, brian-jarvis-aws commented on meeting-minutes/2024/2024-07-03.md
> +3. Demonstation of the live service that uses the plugin
```suggestion
3. Demonstration of the live service that uses the plugin
```

2024-07-16 14:21 UTC, brian-jarvis-aws commented on meeting-minutes/2024/2024-07-03.md
> +   * [Live service](https://cbomdb-frontend-scanservice.openshift-cluster-d465a2b8669424cc1f37658bec09acda-0000.eu-de.containers.appdomain.cloud) aviable to all to test and generate downloadable CBOM
```suggestion
   * [Live service](https://cbomdb-frontend-scanservice.openshift-cluster-d465a2b8669424cc1f37658bec09acda-0000.eu-de.containers.appdomain.cloud) available to all to test and generate downloadable CBOM (Java and Python for now)
```

2024-07-19 21:33 UTC, maximilien reviewed
/lgtm

2024-07-19 21:34 UTC, maximilien commented
Accepted your changes @brian-jarvis-aws

2024-07-22 15:22 UTC, brian-jarvis-aws approved these changes

2024-08-05 13:34 UTC, planetf1 requested changes

2024-08-05 13:34 UTC, planetf1 commented on meeting-minutes/2024/2024-07-03.md
> +
```suggestion
* [ ] Nigel Jones, IBM
```

2024-08-14 13:53 UTC, maximilien commented
@planetf1 can you review please to unblock merge. Thx

2024-08-19 13:06 UTC, maximilien commented on meeting-minutes/2024/2024-07-03.md
> +
Not sure why this is blocking merge

2024-08-21 10:01 UTC, planetf1 requested changes
Updated the attendance. Will watch out for change then add approval as requested.

2024-08-21 10:01 UTC, planetf1 commented on meeting-minutes/2024/2024-07-03.md
> +* [ ] Nigel Jones, IBM
```suggestion
* [x] Nigel Jones, IBM
```

I was on the call

2024-08-21 10:01 UTC, planetf1 commented on meeting-minutes/2024/2024-07-03.md
> +* Nigel Jones (IBM)
```suggestion
```
removed from this section

2024-08-21 16:15 UTC, ryjones commented
@planetf1 check the latest commit

2024-08-28 14:28 UTC, planetf1 approved these changes
thanks for updating

2024-08-28 14:28 UTC, merged