Aug 28 2024 TAC Minutes
PQCA/TAC pull request #47
Opened 2024-08-30 23:57 UTC by KennyPaul

Thanks!
-kenny

2024-09-04 05:50 UTC, baentsch commented on meeting-minutes/2024/2024-08-28-TAC.md
> +Passed 6-0
Can I ask what the meaning of a vote is on a document that is in large parts open/under discussion?

2024-09-10 11:14 UTC, planetf1 requested changes
Fixed up a few minor typos

2024-09-10 11:14 UTC, planetf1 commented on meeting-minutes/2024/2024-08-28-TAC.md
> +* [x] Nigel Jones, IBM [PQP]
```suggestion
* [x] Nigel Jones, IBM [PQCP]
```

2024-09-10 11:14 UTC, planetf1 commented on meeting-minutes/2024/2024-08-28-TAC.md
> +* Chrystals team repo will be ramping up
```suggestion
* Generic C reference implementation (from PQ-Crystals repo) will be ramping up
```

2024-09-10 11:14 UTC, planetf1 commented on meeting-minutes/2024/2024-08-28-TAC.md
> +* A lot of discussions was pulled out of the document
```suggestion
* A lot of discussions were pulled out of the document
```

2024-09-10 11:14 UTC, planetf1 commented on meeting-minutes/2024/2024-08-28-TAC.md
> +* Some aspects of the workj are already part of LFN’s 5G Super blueprint
```suggestion
* Some aspects of the work are already part of LFN’s 5G Super blueprint
```

2024-09-10 11:14 UTC, planetf1 commented on meeting-minutes/2024/2024-08-28-TAC.md
> +* Extension to SonarCube WIP from IBM - likely candidate for a project.
```suggestion
* Extension to SonarQube WIP from IBM - likely candidate for a project.
```

2024-09-10 18:19 UTC, KennyPaul commented on meeting-minutes/2024/2024-08-28-TAC.md
> +Passed 6-0
The meaning is that the vote establishes the document as the official lifecycle policy for PQCA effective Aug 26, 2024.   As is common practice in many communities, issues are open for areas of the document which may, at the sole discretion of the TAC,  result in amendments to the policy. 

-kenny

2024-09-10 20:11 UTC, closed without merging

2024-09-11 10:37 UTC, baentsch commented on meeting-minutes/2024/2024-08-28-TAC.md
> +Passed 6-0
> the vote establishes the document as the official lifecycle policy for PQCA effective Aug 26, 2024 [...] issues [...] open [...] may, at the sole discretion of the TAC, result in amendments

Thanks for the clarification @KennyPaul . I understand your point from a procedural perspective (company majority in the TAC). IMO this runs diametrically counter to the initial claims by @hartm and @maximilien when they wanted OQS to join LF that PQCA would be there to "support the community" (independent of corporate interests).

@dstebila , next to ignoring GOVERNANCE.md files when setting GH access permissions I see this as the so far most blatant example of LF corporate control of PQCA leading to community input to be ignored: Valid & accepted technical concerns are shelved & resolution put "at the sole discretion of the TAC". It seems even the TSC is irrelevant.

This top-down/command-and-control behaviour was exactly what I was afraid of from the moment IBM&LF proposed the take over of OQS -- and I see the concern giving companies control of the project now proven true with this statement & procedure.

Less generally, what value is there to [providing input to the TAC as and when asked for](https://github.com/open-quantum-safe/tsc/blob/main/meetings/2024-06-27/minutes.md#4-report-from-tac-representative) when it's ultimately getting ignored anyway as per the above?

Also tagging @brian-jarvis-aws as the person identified in the last TSC meeting as responsible for this activity: Wouldn't it be better to have an open discussion and mutual agreement around disputed topics -- also taking the interest of end users and independent contributors into account -- rather than a "take-it-or-leave-it" stance as expressed in the above?