Added minutes
PQCA/TAC pull request #5
Opened 2024-04-09 17:40 UTC by maximilien

* minutes
* list of attendees
* actuion items

2024-04-09 17:42 UTC, maximilien commented
Please review ASAP @ryjones @thb-sb @Naomi-Wash and merge

Will share in my email to mailing list to announce next meeting and agenda

Thanks

2024-04-09 18:08 UTC, ryjones commented
now that I see what you want to do, I'll wait for a vote to approve from a TAC member

2024-04-09 18:13 UTC, ashman-p requested changes

2024-04-09 18:13 UTC, ashman-p commented on meeting-minutes/2024/2024-04-03-TAC.md
> +* [x] Thomas Ashley, Cisco
```suggestion
* [x] Norman Ashley, Cisco
```

2024-04-09 20:27 UTC, brian-jarvis-aws approved these changes

2024-04-09 22:44 UTC, ashman-p approved these changes

2024-04-10 09:26 UTC, planetf1 requested changes
Added some updates/corrections.

2024-04-10 09:26 UTC, planetf1 commented on meeting-minutes/2024/2024-04-03-TAC.md
> +  a. Nigel updates [link to PDF presentation]
```suggestion
  a. Nigel updates [link to PDF presentation](https://hackathon.pqcodepackage.org/202404/summary.html)
```

2024-04-10 09:26 UTC, planetf1 commented on meeting-minutes/2024/2024-04-03-TAC.md
> +* [x] Hart Montgomery, LF
Do all attendees get recorded, in addition to voting members.

Maybe
```suggestion
* [x] Hart Montgomery, LF
* [x] Nigel Jones, IBM [**non-voting attendee**]
```

2024-04-10 09:26 UTC, planetf1 commented on meeting-minutes/2024/2024-04-03-TAC.md
> +  c. Use GH discussions for project and discord for
I think we also discussed using the mailing list calendar for meeting invites (ical feed). Perhaps I misremembered.

2024-04-10 09:26 UTC, planetf1 commented on meeting-minutes/2024/2024-04-03-TAC.md
> +  a. Hart shared template lifecycle that takes from Hyperledger and other projects [link to doc]
```suggestion
  a. Hart shared template lifecycle that takes from Hyperledger and other projects  [link to doc](https://docs.google.com/document/d/1NV-0vNgXWdc81oqT0jv0C-9Funb8dySS06u90ghF-X4/edit?usp=sharing)
```

2024-04-10 09:26 UTC, planetf1 commented on meeting-minutes/2024/2024-04-03-TAC.md
> +* [ ] Propose the 3 new working groups:  Algos, Tooling / Misc, and Docs / Education / Website as sissues [Max]
```suggestion
* [ ] Propose the 3 new working groups:  Algos, Tooling / Misc, and Docs / Education / Website as issues [Max]
```

2024-04-10 12:16 UTC, ryjones commented on meeting-minutes/2024/2024-04-03-TAC.md
> +* [x] Hart Montgomery, LF
@planetf1 I only record the voting members.

2024-04-10 12:16 UTC, ryjones commented on meeting-minutes/2024/2024-04-03-TAC.md
> +  c. Use GH discussions for project and discord for
working on it

2024-04-10 12:25 UTC, ryjones commented
@planetf1 please merge if you agree

2024-04-10 13:03 UTC, planetf1 commented
An additional observation.

We have a bulleted list of attendees - I presume these are the TAC members

How about having this in two parts ie

## TAC members

- [ ] A tac member

## Additional attendees 

- [ ] A non member 

(For the record I attended, but am not a tac member)

2024-04-10 13:23 UTC, ryjones commented
> An additional observation.
> 
> We have a bulleted list of attendees - I presume these are the TAC members
> 

Yes. Usually only track voting members. I have no preference about tracking non-voting attendees - if that's what the project wants, it's fine by me

2024-04-10 13:52 UTC, thb-sb approved these changes

2024-04-10 14:07 UTC, merged