Create stale.yml
PQCA/TAC pull request #52
Opened 2024-09-25 15:57 UTC by maximilien

As per TAC call today creating this GH action that will mark issues and PRs as stalled if they have no comments after some period of time

2024-09-25 15:58 UTC, maximilien commented
CC: @brian-jarvis-aws @n1ckl0sk0rtge @planetf1 @ryjones @KennyPaul for any feedback and approval to merge

2024-09-25 16:32 UTC, ryjones approved these changes

2024-09-26 07:18 UTC, n1ckl0sk0rtge commented on .github/workflows/stale.yml
> +        stale-issue-message: 'Stale issue message'
```suggestion
        stale-issue-message: 'This issue has been automatically marked as stale due to inactivity. It will be closed if no further activity occurs within 60 days. Thank you for your contributions.'
```

2024-09-26 07:19 UTC, n1ckl0sk0rtge commented on .github/workflows/stale.yml
> +        stale-pr-message: 'Stale pull request message'
```suggestion
        stale-pr-message: 'This pull request has been automatically marked as stale due to lack of recent updates. It will be closed if no further activity occurs within 7 days. Please review and update if needed.'
```

2024-09-26 07:21 UTC, n1ckl0sk0rtge requested changes
Maybe adding more meaningful comments.

2024-10-07 13:47 UTC, brian-jarvis-aws commented on .github/workflows/stale.yml
> +      with:
If I understand the action correctly, I think some parameters are missing. According to [the docs](https://github.com/actions/stale), I'd expect at least `days-before-stale` and `days-before-close`.

2024-11-07 09:35 UTC, planetf1 commented on .github/workflows/stale.yml
> +      with:
the defaults for those are 60/7

Two values I've used before are`exempt-pr-labels` / `exempt-issue-labels` . Though there is an argument this can be overused (it was in my previous project), so the group may prefer that this has to be done by adding an explanation as to why, and manually re-opening

2024-11-07 09:47 UTC, planetf1 approved these changes
Happy with proposed change. there are comments, but actioning imo is optional

2025-02-27 15:35 UTC, maximilien commented
Let's merge and we can address the changes as separate PR @ryjones.

Thanks

2025-02-27 15:35 UTC, merged