draft for approval
PQCA/TAC pull request #53
Opened 2024-10-02 16:36 UTC by KennyPaul

2024-10-06 22:28 UTC, brian-jarvis-aws commented on meeting-minutes/2024/2024-09-25-TAC.md
> +* PQPC
PQPC --> PQCP

2024-10-06 22:28 UTC, brian-jarvis-aws commented on meeting-minutes/2024/2024-09-25-TAC.md
> +* Implementation of kyber (sp) & mlkem(sp)
Kyber, ML-KEM

2024-10-06 22:28 UTC, brian-jarvis-aws commented on meeting-minutes/2024/2024-09-25-TAC.md
> +* Many non functional improvemens like moving things to GHI
improvements

2024-10-06 22:28 UTC, brian-jarvis-aws commented on meeting-minutes/2024/2024-09-25-TAC.md
> +* libjade(sp) looking to implementation for alignment
Spelling is correct

2024-10-06 22:28 UTC, brian-jarvis-aws commented on meeting-minutes/2024/2024-09-25-TAC.md
> +* PR open for krystals(sp) please look at the pr
Assuming this is referring to CRYSTALS. ([ref](https://pq-crystals.org))

2024-10-06 22:28 UTC, brian-jarvis-aws commented on meeting-minutes/2024/2024-09-25-TAC.md
> +* collegeag QKD quant key dist
Colleague
QKD = Quantum Key Distribution

2024-11-07 09:43 UTC, planetf1 commented on meeting-minutes/2024/2024-09-25-TAC.md
> +* PQPC
```suggestion
* PQCP
```

2024-11-07 09:43 UTC, planetf1 commented on meeting-minutes/2024/2024-09-25-TAC.md
> +* Implementation of kyber (sp) & mlkem(sp)
```suggestion
* Implementation of Kyber & ML-KEM
```

2024-11-07 09:44 UTC, planetf1 commented on meeting-minutes/2024/2024-09-25-TAC.md
> +* Many non functional improvemens like moving things to GHI
```suggestion
* Many non functional improvements like moving things to GHI
```

2024-11-07 09:44 UTC, planetf1 commented on meeting-minutes/2024/2024-09-25-TAC.md
> +* libjade(sp) looking to implementation for alignment
```suggestion
* libjade looking to implementation for alignment
```

2024-11-07 09:45 UTC, planetf1 commented on meeting-minutes/2024/2024-09-25-TAC.md
> +* PR open for krystals(sp) please look at the pr
```suggestion
* PR open for merging PQCrystals code : please look at the pr in mlkem-c-generic
```

2024-11-07 09:46 UTC, planetf1 commented on meeting-minutes/2024/2024-09-25-TAC.md
> +* collegeag QKD quant key dist
```suggestion
* Colleague - QKD (Quantum Key Distribution)
```

2024-11-07 09:46 UTC, planetf1 requested changes
See proposed changes, mostly based on @brian-jarvis-aws review

2024-12-03 14:45 UTC, brian-jarvis-aws approved these changes

2024-12-11 23:12 UTC, closed without merging

2024-12-12 23:41 UTC, SWilson4 commented
@KennyPaul just checking—did you mean to close this PR or merge it?